<?php

/**
 * tbl_ligueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_ligueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_ligueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_ligue');
    }
}