<?php

/**
 * tbl_federationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_federationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_federationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_federation');
    }
}