<?php

/**
 * tbl_avoirTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_avoirTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_avoirTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_avoir');
    }
}