<?php

/**
 * tbl_prixlicenceTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_prixlicenceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_prixlicenceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_prixlicence');
    }

    public function getPrixByKey($nIdTypeLicence, $nIdFederation)
    {
        $q = $this->createQuery('q');
        $q->where('id_typelicence = ?', $nIdTypeLicence)
          ->andWhere('id_federation = ?', $nIdFederation);

        return $q->fetchOne();
    }
}