<?php

/**
 * tbl_clubTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_clubTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_clubTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_club');
    }
}