<?php

/**
 * tbl_genTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_genTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_genTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_gen');
    }
}