<?php

/**
 * tbl_licenceTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_licenceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_licenceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_licence');
    }

    public function countLicenceClub($nIdClub)
    {
        $q = $this->createQuery('l');
        $q->where('id_club = ?', $nIdClub);
        $nMember = $q->execute()->count();
        return $nMember;
    }
}