<?php

/**
 * tbl_saisonTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_saisonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_saisonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_saison');
    }

    public function getSaisonLicence()
    {
        $oSaisons = Doctrine::getTable('tbl_saison')->findAll();
        $aSaison = array();
        $aSaison[0] = "";
        foreach ($oSaisons as $oSaison)
        {
            $aSaison[$oSaison->getId()] = $oSaison->getYearLicence();
        }
        return $aSaison;
    }
}