<?php

/**
 * tbl_mandatTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_mandatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_mandatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_mandat');
    }

    public function findOlderPoste($nIdProfil)
    {
        $q = $this->createQuery('q');
        $q->andWhere('id_profil = ?', $nIdProfil)
          ->orderBy('date_begin DESC');
        return $q->fetchOne();

    }
}