<?php

/**
 * tbl_profilTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_profilTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_profilTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_profil');
    }
    public function findByKeyword($keyword, $bLimit=true)
    {
        $sName = mb_strtoupper($keyword);
        $q = $this->createQuery('p')
              ->where('upper(p.first_name) LIKE ?', $sName.'%')
              ->orWhere('upper(p.last_name) LIKE ?', $sName.'%');
        if ($bLimit) {
            $q->limit(0, 20);
        }
        return $q->execute();
    }

    public function findByKeywordClub($keyword, $club, $bLimit=true)
    {
        $sName = mb_strtoupper($keyword);
        $q = $this->createQuery('p')
              ->leftJoin('p.tbl_licence l')
              ->leftJoin('l.tbl_club c')
              ->where('l.id_club = ?', $club->getId())
              ->andWhere('upper(p.last_name) LIKE ? OR upper(p.first_name) LIKE ?', array($sName.'%', $sName.'%'));
              //->andWhere('upper(p.first_name) LIKE ?', $sName.'%');
        if ($bLimit) {
            $q->limit(0, 20);
        }
        return $q->execute();
    }

}
