<?php

/**
 * tbl_affectationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_affectationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_affectationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_affectation');
    }
}