<?php

/**
 * tbl_bordereauTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_bordereauTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_bordereauTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_bordereau');
    }
}