<?php

/**
 * tbl_bordereau
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class tbl_bordereau extends Basetbl_bordereau
{
    public function delete(Doctrine_Connection $conn = null)
    {
        $oPayments = $this->getTblPayment();
        foreach ($oPayments as $oPayment) {
            $oPayment->setIdBordereau(null)->save();
        }
        $oAvoirs = $this->getTblAvoir();
        foreach ($oAvoirs as $oAvoir) {
            $oAvoir->setIdBordereau(null)->save();
        }
        return parent::delete($conn);
    }
}
