<?php

/**
 * tbl_paymentTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_paymentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_paymentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_payment');
    }

    public function findPaymentByUser($nIdUser)
    {
        $q = $this->createQuery('p');
        $q->andWhere('p.id_user = ?', $nIdUser)
          ->andWhere('p.is_payed = ?', false)
          ->andWhere('p.is_brouillon = true');

        return $q->execute();
    }

    public function findPaymentByLigue($nIdLigue, $bSaisie=false)
    {
        $q = $this->createQuery('p');
        $q->leftJoin('p.tbl_club c')
          ->leftJoin('c.tbl_ligue l')
          ->andWhere('l.id = ?', $nIdLigue)
          ->andWhere('p.is_payed = ?', false);
        if ($bSaisie) {
          $q->andWhere('p.is_brouillon = true');
        }
        return $q->execute();
    }
    public function findPaymentClub($nIdClub, $bSaisie=false)
    {
        $q = $this->createQuery('p');
        $q->andWhere('p.id_club = ?', $nIdClub)
          ->andWhere('p.is_payed = ?', false);
        if ($bSaisie) {
          $q->andWhere('p.is_brouillon = true');
        } else {
          $q->andWhere('p.is_brouillon = false');
        }
        return $q->execute();
    }

    public function getAmountByLigue($nIdLigue)
    {
        $q = Doctrine_Query::create()
          ->select('SUM(p.amount) AS AmountTotal')
          ->from('tbl_payment p')
          ->leftJoin('p.tbl_club c')
          ->leftJoin('c.tbl_ligue l')
          ->andWhere('l.id = ?', $nIdLigue)
          ->andWhere('p.is_payed = ?', false);
        $result = $q->fetchOne();
        return $result['AmountTotal'];
    }

    public function getAmountClub($nIdClub)
    {
        $q = Doctrine_Query::create()
          ->select('SUM(p.amount) AS AmountTotal')
          ->from('tbl_payment p')
          ->andWhere('p.id_club = ?', $nIdClub)
          ->andWhere('p.is_brouillon = ?', false)
          ->andWhere('p.is_payed = ?', false);
        $result = $q->fetchOne();
        return $result['AmountTotal'];
    }

    public function getAmountClubBordereau($nIdClub, $nIdBordereau)
    {
        $q = Doctrine_Query::create()
          ->select('SUM(p.amount) AS AmountTotal')
          ->from('tbl_payment p')
          ->andWhere('p.id_club = ?', $nIdClub)
          ->andWhere('p.is_brouillon = ?', false)
          ->andWhere('p.id_bordereau = ?', $nIdBordereau)
          ->andWhere('p.is_payed = ?', false);
        $result = $q->fetchOne();
        return $result['AmountTotal'];
    }

    public function validSaisie($nIdClub, $nIdUser)
    {
        $q = $this->createQuery('p');
        $q->where('p.id_club = ?', $nIdClub)
          ->andWhere('p.id_user = ?', $nIdUser)
          ->andWhere('p.is_brouillon = true');

        $oPaiements = $q->execute();
        foreach ($oPaiements as $oPaiement)
        {
          $oPaiement->setIsBrouillon(false)->save();
        }
    }

    public function cancelSaisie($nIdClub, $nIdUser)
    {
        $q = $this->createQuery('p');
        $q->where('p.id_club = ?', $nIdClub)
          ->andWhere('p.id_user = ?', $nIdUser)
          ->andWhere('p.is_brouillon = true');

        $oPaiements = $q->execute();
        foreach ($oPaiements as $oPaiement)
        {
          $oPaiement->delete();
        }
    }

    public function validSaisieByUser($nIdUser)
    {
        $q = $this->createQuery('p');
        $q->andWhere('p.id_user = ?', $nIdUser)
          ->andWhere('p.is_brouillon = true');

        $oPaiements = $q->execute();
        foreach ($oPaiements as $oPaiement)
        {
          $oPaiement->setIsBrouillon(false)->save();
        }
    }

    public function cancelSaisieByUser($nIdUser)
    {
        $q = $this->createQuery('p');
        $q->andWhere('p.id_user = ?', $nIdUser)
          ->andWhere('p.is_brouillon = true');

        $oPaiements = $q->execute();
        foreach ($oPaiements as $oPaiement)
        {
          $oPaiement->delete();
        }
    }
    public function retrieveByValide(Doctrine_Query $q) {
        $q = $this->createQuery('q');
        $q->andWhere('is_brouillon = false');

        return $q;
    }

    public function findToDdelete($sType, $nIdUser, $nIdLicence)
    {
        $q = $this->createQuery('p');
        $q->andWhere('p.relation_table = ?', $sType)
          ->andWhere('p.id_user = ?', $nIdUser)
          ->andWhere('p.is_payed = ?', false)
          ->andWhere('p.id_licence = ?', $nIdLicence);

        $oPaiements = $q->execute();
        foreach ($oPaiements as $oPaiement)
        {
          $oPaiement->delete();
        }

    }

    public function findPayment($sType, $nIdUser, $nIdLicence)
    {
        $q = $this->createQuery('p');
        $q->andWhere('p.relation_table = ?', $sType)
          ->andWhere('p.id_user = ?', $nIdUser)
          ->andWhere('p.id_licence = ?', $nIdLicence);

        return $q->execute();
    }

    public function findPaymentLic($nIdProfil)
    {
        $q = $this->createQuery('p');
        $q->andWhere('p.is_payed = ?', false)
          ->andWhere('p.is_brouillon = ?', false)
          ->andWhere('p.id_club is null')
          ->andWhere('p.id_ligue is null')
          ->andWhere('p.id_licence is null')
          ->andWhere('p.id_profil = ?', $nIdProfil);

        return $q->execute();
    }

    public function findPaymentClubBordereau($nIdClub, $nBordereau=null)
    {
        $q = $this->createQuery('p');
        $q->andWhere('p.id_club = ?', $nIdClub)
          ->andWhere('p.is_payed = ?', false)
          ->andWhere('p.is_brouillon = false');
        if ($nBordereau == null) {
          $q->andWhere('p.id_bordereau is null');
        } else {
          $q->andWhere('p.id_bordereau = ?', $nBordereau);
        }
        return $q->execute();
    }
}