<?php

/**
 * tbl_tracabilityTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_tracabilityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_tracabilityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_tracability');
    }

    public function retrieveSortDate(Doctrine_Query $q) {
      $q = $this->createQuery('q');
      $q->orderBy('date_connexion DESC');
      return $q;
    }
}