<?php

/**
 * tbl_codepostauxTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_codepostauxTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_codepostauxTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_codepostaux');
    }
}