<?php

/**
 * tbl_licenceTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_licenceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_licenceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_licence');
    }

    public function countLicenceClub($nIdClub, $sYearLicence)
    {
        $q = $this->createQuery('l');
        $q->where('id_club = ?', $nIdClub)
          ->andWhere("l.year_licence = ?", $sYearLicence);
        $nMember = $q->execute()->count();
        if ($nMember == 0) {
            return 1;
        } else {
            return $nMember+1;
        }
    }
    public function getDateLicence()
      {
        if (date('d') >= 1 && date('m') >= 7) {
          $startDate = date('Y');
          $endDate   = date('Y')+1;
        } else {
          $startDate = date('Y')-1;
          $endDate   = date('Y');
        }
        $sDate = (string) $startDate.'/'.(string) $endDate;

        return $sDate;
    }

    public function retrieveByClub(Doctrine_Query $q) {
        $q = $this->createQuery('q');
        if (sfContext::getInstance()->getUser()->isClub()) {
            $oClub = sfContext::getInstance()->getUser()->getClub();
            $q->where('id_club = ?', $oClub->getId());
        } elseif (sfContext::getInstance()->getUser()->isLigue()) {
            $oLigue = sfContext::getInstance()->getUser()->getLigue();
            $aClub = array();
            foreach ($oLigue->getTblClub() as $oClub)
            {
                $aClub[] = $oClub->getId();
            }
            if (empty($aClub))
            {
                $aClub[] = 0;
            }
            $q->andWhereIn('id_club', $aClub);
        }

        $q->andWhereIn('year_licence', $this->getDateLicence());

        return $q;
    }

    public function validSaisie($isClub, $isLigue, $nKey)
    {
        $q = $this->createQuery('q');
        if ($isClub) {
            $q->where('id_club = ?', $nKey);
        } elseif ($isLigue) {
            $oLigue = Doctrine::getTable('tbl_ligue')->find($nKey);
            $aClub = array();
            foreach ($oLigue->getTblClub() as $oClub)
            {
                $aClub[] = $oClub->getId();
            }
            if (empty($aClub))
            {
                $aClub[] = 0;
            }
            $q->andWhereIn('id_club', $aClub);
        }
        $q->andWhere('is_brouillon = ?', true);

        $oLicences = $q->execute();

        foreach ($oLicences as $oLicence)
        {
            $oLicence->setIsBrouillon(false)->save();
        }
    }

    public function validSaisieByUser($nIdUser)
    {
        $q = $this->createQuery('q');

        $q->andWhere('id_user = ?', $nIdUser)
          ->andWhere('is_brouillon = ?', true);

        $oLicences = $q->execute();

        foreach ($oLicences as $oLicence)
        {
            $oLicence->setIsBrouillon(false)->save();
        }
    }

    public function cancelSaisie($isClub, $isLigue, $nKey)
    {
        $q = $this->createQuery('q');
        if ($isClub) {
            $q->where('id_club = ?', $nKey);
        } elseif ($isLigue) {
            $oLigue = Doctrine::getTable('tbl_ligue')->find($nKey);
            $aClub = array();
            foreach ($oLigue->getTblClub() as $oClub)
            {
                $aClub[] = $oClub->getId();
            }
            if (empty($aClub))
            {
                $aClub[] = 0;
            }
            $q->andWhereIn('id_club', $aClub);
        }
        $q->andWhere('is_brouillon = ?', true);

        $oLicences = $q->execute();

        foreach ($oLicences as $oLicence)
        {
            $oLicence->delete();
        }
    }

    public function cancelSaisieByUser($nIdUser)
    {
        $q = $this->createQuery('q');

        $q->andWhere('id_user = ?', $nIdUser)
          ->andWhere('is_brouillon = ?', true);

        $oLicences = $q->execute();

        foreach ($oLicences as $oLicence)
        {
            $oLicence->delete();
        }
    }

    public function findSaisie($isClub, $isLigue, $nKey, $nUser)
    {
        $q = $this->createQuery('q');
        if ($isClub) {
            $q->where('id_club = ?', $nKey);
        } elseif ($isLigue) {
            $oLigue = Doctrine::getTable('tbl_ligue')->find($nKey);
            $aClub = array();
            foreach ($oLigue->getTblClub() as $oClub)
            {
                $aClub[] = $oClub->getId();
            }
            if (empty($aClub))
            {
                $aClub[] = 0;
            }
            $q->andWhereIn('id_club', $aClub);
        }
        $q->andWhere('is_brouillon = ?', true)
          ->andWhere('id_user = ?', $nUser);

        return $q->execute();
    }

    public function findSaisieByUser($nUser)
    {
        $q = $this->createQuery('q');
        $q->andWhere('is_brouillon = ?', true)
          ->andWhere('id_user = ?', $nUser);

        return $q->execute();
    }
}