<?php

/**
 * tbl_typelicenceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_typelicenceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_typelicenceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_typelicence');
    }
}