<?php

/**
 * tbl_typelicence
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class tbl_typelicence extends Basetbl_typelicence
{
    public function __toString()
    {
        return $this->getLib();
    }
}
