<?php

/**
 * tbl_avoirTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_avoirTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_avoirTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_avoir');
    }

    public function findAvoirByUser($nIdUser)
    {
        $q = $this->createQuery('p');
        $q->andWhere('p.id_user = ?', $nIdUser)
          ->andWhere('p.is_used = ?', false)
          ->andWhere('p.is_brouillon = true');

        return $q->execute();
    }

    public function findAvoirByLigue($nIdLigue, $bSaisie=false)
    {
        $q = $this->createQuery('p');
        $q->leftJoin('p.tbl_club c')
          ->leftJoin('c.tbl_ligue l')
          ->andWhere('l.id = ?', $nIdLigue)
          ->andWhere('p.is_used = ?', false);
        if ($bSaisie) {
          $q->andWhere('p.is_brouillon = true');
        }
        return $q->execute();
    }
    public function findAvoirClub($nIdClub, $bSaisie=false)
    {
        $q = $this->createQuery('a');
        $q->andWhere('a.id_club = ?', $nIdClub)
          ->andWhere('a.is_used = ?', false);
        if ($bSaisie) {
          $q->andWhere('a.is_brouillon = true');
        }
        return $q->execute();
    }

    public function getAmountAvoirClub($nIdClub)
    {
        $q = Doctrine_Query::create()
          ->select('SUM(a.amount) AS AmountTotal')
          ->from('tbl_avoir a')
          ->andWhere('a.id_club = ?', $nIdClub)
          ->andWhere('a.is_used = ?', false);
        $result = $q->fetchOne();
        return $result['AmountTotal'];
    }

    public function getAmountAvoirClubBordereau($nIdClub, $nIdBordereau)
    {
        $q = Doctrine_Query::create()
          ->select('SUM(a.amount) AS AmountTotal')
          ->from('tbl_avoir a')
          ->andWhere('a.id_club = ?', $nIdClub)
          ->andWhere('a.id_bordereau = ?', $nIdBordereau)
          ->andWhere('a.is_used = ?', false);
        $result = $q->fetchOne();
        return $result['AmountTotal'];
    }

    public function validSaisie($nIdClub, $nIdUser)
    {
        $q = $this->createQuery('a');
        $q->where('a.id_club = ?', $nIdClub)
          ->andWhere('a.id_user = ?', $nIdUser)
          ->andWhere('a.is_brouillon = true');

        $oPaiements = $q->execute();
        foreach ($oPaiements as $oPaiement)
        {
          $oPaiement->setIsBrouillon(false)->save();
        }
    }

    public function cancelSaisie($nIdClub, $nIdUser)
    {
        $q = $this->createQuery('a');
        $q->where('a.id_club = ?', $nIdClub)
          ->andWhere('a.id_user = ?', $nIdUser)
          ->andWhere('a.is_brouillon = true');

        $oPaiements = $q->execute();
        foreach ($oPaiements as $oPaiement)
        {
          $oPaiement->delete();
        }
    }

    public function validSaisieByUser($nIdUser)
    {
        $q = $this->createQuery('a');
        $q->andWhere('a.id_user = ?', $nIdUser)
          ->andWhere('a.is_brouillon = true');

        $oPaiements = $q->execute();
        foreach ($oPaiements as $oPaiement)
        {
          $oPaiement->setIsBrouillon(false)->save();
        }
    }

    public function cancelSaisieByUser($nIdUser)
    {
        $q = $this->createQuery('a');
        $q->andWhere('a.id_user = ?', $nIdUser)
          ->andWhere('a.is_brouillon = true');

        $oPaiements = $q->execute();
        foreach ($oPaiements as $oPaiement)
        {
          $oPaiement->delete();
        }
    }

    public function retrieveByValide(Doctrine_Query $q) {
        $q = $this->createQuery('q');
        $q->andWhere('is_brouillon = false');

        return $q;
    }
    public function findAvoirClubBordereau($nIdClub)
    {
        $q = $this->createQuery('p');
        $q->andWhere('p.id_club = ?', $nIdClub)
          ->andWhere('p.is_used = ?', false)
          ->andWhere('p.id_bordereau = ?', null)
          ->andWhere('p.is_brouillon = false');
        return $q->execute();
    }
}