<?php

/**
 * tbl_typelicenceTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_typelicenceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_typelicenceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_typelicence');
    }
    public function retrieveSortTypeLicenceList(Doctrine_Query $q) {
      $q = $this->createQuery('q');
      $q->orderBy('rank ASC');
      return $q;
    }
    public function getTypeLicenceRank() {
      $q = $this->createQuery('a');
      $rootAlias = $q->getRootAlias();
      $q->orderBy($rootAlias.'.rank ASC');

      return $q->execute();
    }
}