<?php

/**
 * tbl_paymentTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_paymentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_paymentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_payment');
    }

    public function findPaymentLicByClub($nIdClub)
    {
        $q = $this->createQuery('p');
        $q->leftJoin('p.tbl_licence l')
          ->andWhere('l.id_club = ?', $nIdClub)
          ->andWhere('p.is_payed = ?', false);

        return $q->execute();
    }
    public function findPaymentClub($nIdClub)
    {
        $q = $this->createQuery('p');
        $q->andWhere('p.id_club = ?', $nIdClub)
          ->andWhere('p.is_payed = ?', false);

        return $q->execute();
    }
}