<?php

/**
 * tbl_typepaymentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_typepaymentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_typepaymentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_typepayment');
    }
}