<?php

/**
 * tbl_prixunitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_prixunitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_prixunitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_prixunit');
    }
}