<?php

/**
 * tbl_codepostauxTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_codepostauxTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_codepostauxTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_codepostaux');
    }

    public function findByKeyword($keyword)
    {
        $sVille = mb_strtoupper($keyword);
        $q = $this->createQuery('c')
              ->where('c.ville LIKE ?', $sVille.'%')
              ->orWhere('c.code_postaux LIKE ?', $sVille.'%')
              ->limit(20);

        return $q->execute();
    }
}