<?php

/**
 * tbl_licenceTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_licenceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_licenceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_licence');
    }

    public function countLicenceClub($nIdClub)
    {
        $q = $this->createQuery('l');
        $q->where('id_club = ?', $nIdClub);
        $nMember = $q->execute()->count();
        return $nMember;
    }
    public function retrieveByClub(Doctrine_Query $q) {
        $q = $this->createQuery('q');
        if (sfContext::getInstance()->getUser()->isClub()) {
            $oClub = sfContext::getInstance()->getUser()->getClub();
            $q->where('id_club = ?', $oClub->getId());
        } elseif (sfContext::getInstance()->getUser()->isLigue()) {
            $oLigue = sfContext::getInstance()->getUser()->getLigue();
            $aClub = array();
            foreach ($oLigue->getTblClub() as $oClub)
            {
                $aClub[] = $oClub->getId();
            }
            if (empty($aClub))
            {
                $aClub[] = 0;
            }
            $q->andWhereIn('id_club', $aClub);
        }

        return $q;
    }
}