<?php

/**
 * tbl_clubTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_clubTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_clubTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_club');
    }

    public function getClubLigue()
    {
        $oLigue = sfContext::getInstance()->getUser()->getLigue();
        foreach ($oLigue->getTblClub() as $oClub)
        {
            $aClub[] = $oClub->getId();
        }
        if (empty($aClub))
        {
            $aClub[] = 0;
        }

        $q = $this->createQuery('q');
        $q->andWhereIn('id', $aClub);

        return $q;
    }
}