<?php

/**
 * tbl_saisonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_saisonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_saisonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_saison');
    }
}