<?php

/**
 * tbl_addressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_addressTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_addressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_address');
    }
}