<?php

/**
 * tbl_categoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_categoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_categoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_category');
    }
}