<?php

/**
 * tbl_tarifreduitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_tarifreduitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_tarifreduitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_tarifreduit');
    }
}