<?php

/**
 * tbl_paramsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tbl_paramsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tbl_paramsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tbl_params');
    }
}