# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
prod:
  mail:
    test: ffst@free.fr
    contact: contact@laffst.com
    returnpath: contact@laffst.com
  paypal:
    business:  ffst@free.fr
    url: https://www.paypal.com/cgi-bin/webscr
    cancel: http://www.laffst.com/paypal_cancel.php
    notify: http://www.laffst.com/notifypaypal.php
    return: http://www.laffst.com/validation.php
sandbox:
  mail:
    test: ffst@free.fr
    contact: contact@laffst.com
    returnpath: contact@laffst.com
  paypal:
    business: tgilbe_1273247786_biz@tgprojets.fr
    url: https://www.sandbox.paypal.com/cgi-bin/webscr
    cancel: http://sandbox.laffst.com/paypal_cancel.php
    notify: http://sandbox.laffst.com/notifypaypal_sb.php
    return: http://sandbox.laffst.com/validation.php
all:
  mail:
    test: t.gilbert1@gmail.com
    contact: tgilbert@tgilbert-fixe
    returnpath: tgilbert@tgilbert-fixe
  paypal:
    business: tgprojets.fr
    url: notifypaypal_dev
    cancel: paypal_cancel.php
    notify: notifypaypal_dev.php
    return: validation.php
  images:
    logo: logo
    thumbnail: thumbnail
    profil: profil
  majordate:
    renew_day: '31'
    renew_month: '10'
    int_day: '15'
    int_month: '11'