generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tbl_tarifreduit
    theme:                 admin
    css:                   admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tbl_tarifreduit
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        lib:
          label: Libellé
        prix:
          label: Prix en €
      list:
        title: Liste tarifs réduits
        max_per_page: 20
        batch_actions: {}
        actions: {}
        object_actions:
          _edit: ~
      filter:
        class: false
      form:
        display: [lib, prix]
      edit:
        title: Edition du prix %%lib%%
      new:
        title: Nouveau prix
