<?php

/**
 * sfGuardUserTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }

    public function findByKeyword($keyword)
    {
        $sName = mb_strtoupper($keyword);

          $q = $this->createQuery('p')
                ->where('upper(p.first_name) LIKE ?', $sName.'%')
                ->orWhere('upper(p.last_name) LIKE ?', $sName.'%')
                ->orWhere('upper(p.username) LIKE ?', $sName.'%')
                ->limit(0, 20);

        return $q->execute();
    }

}