generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tbl_licence
    theme:                 admin
    css:                   admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          licence_old
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        list_yearlicence:
          label: Année de licence
        is_valid:
          label: Licence Valide
        email:
          help: Requis
        first_name:
          label: Prénom
        last_name:
          label: Nom
        birthday:
          label: Date anniversaire
          help: Requis
        address1:
          label: Adresse
          help: Requis
        address2:
          label: Adresse complémentaire
        tel:
          label: Téléphone
        gsm:
          label: Portable
        fax:
          label: Fax
        id_club:
          label: Club
        id_category:
          label: Catégorie
        id_familly:
          help: Licence du tuteur (valide)
        id_typelicence:
          label: Type de licence
        is_familly:
          label: Famille
        date_medical:
          label: Date certificat médical
        tbl_club:
          label: Club
        tbl_category:
          label: Catégorie
        tbl_typelicence:
          label: Type de licence
        check_date:
          label: Validation
        tbl_profil:
          label: Licencié
        num:
          label: Numéro de licence
        is_brouillon:
          label: Brouillon (encours de saisie)
        is_cancel:
          label: Licence annulée
      list:
        title: Liste des licenciés
        display: [num, is_cancel, tbl_profil, tbl_club, tbl_typelicence, tbl_category, _check_date, date_validation]
        table_method: retrieveByClubOld
        max_per_page: 20
        batch_actions: {}
        actions:
          _new:
            credentials: [ValidLicence]
          export_data:
            label: Export vers Excel
            credentials: [stats]
            params:
              class: sb_bouton_list
        object_actions:
          imprimer:
            credentials: [ValidLicence]
            params:
              class: print_icon
          cancel_licence:
            credentials: [ValidLicence]
            label: Annulée licence
            params:
              class: cancel_icon
          _edit:
            credentials: [ValidLicence]
          show:
            label: Voir
            params:
              class: zoom_icon
      filter:
        display: [list_yearlicence, num, last_name, first_name, id_typelicence, international, id_category, id_club, is_valid]
      form:
        class: tbl_licenceoldForm
        fields:
          id_club:
            label: Club
            help: Requis
          id_typelicence:
            label: Type de licence
            help: Requis
          id_category:
            label: Catégorie
            help: Requis
          is_medical:
            label: Certificat valide
          is_familly:
            label: Tarif réduit famille
          first_name:
            label: Prénom
            help: Requis
          last_name:
            label: Nom
            help: Requis
          year_licence:
            label: Année de la licence
            help: 20XX/20XX (Requis)
          is_foreign:
            label: Adresse à l'étranger
          country:
            label: Pays
            help: Requis
          cp_foreign:
            label: Code postal
            help: Requis
          city_foreign:
            label: Ville
            help: Requis
          id_codepostaux:
            help: Requis
          lastname_doctor:
            label: Nom Docteur
          firstname_doctor:
            label: Prénom Docteur
          rpps:
            label: N° RPPS
      edit:
        title: Edition de la licence de %%tbl_profil%%
        actions:
          _list:
          _save:
        display:
          "Profile": [_image_profil, sexe, image, email, last_name, first_name, birthday, id_profil]
          "Adresse": [_foreign, is_foreign, country, cp_foreign, city_foreign, id_codepostaux, address1, address2, tel, gsm, fax, id_address]
          "Licence": [_yearlicence, _checkmedical, id_club, id_typelicence, id_category, international, race_nordique, cnil, is_medical, date_medical, lastname_doctor, firstname_doctor, rpps, date_validation]
      new:
        title: Nouvelle licence
        actions:
          _list:
          _save:
          _save_and_add:
        display:
          "Rechercher licencié existant": [id_profil, _profil_exist]
          "Saisir licencié": [sexe, image, email, last_name, first_name, birthday]
          "Adresse": [_foreign, is_foreign, country, cp_foreign, city_foreign, id_codepostaux, address1, address2, tel, gsm, fax, id_address]
          "Licence": [year_licence, _checkmedical,  id_club, id_typelicence, id_category, international, race_nordique, cnil, is_medical, date_medical, lastname_doctor, firstname_doctor, rpps, date_validation]

