generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tbl_bordereau
    theme:                 admin
    css:                   admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tbl_bordereau
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        num:
          label: N°
        amount:
          label: Montant
        is_payed:
          label: Payé
        tbl_club:
          label: Nom du club
        tbl_typepayment:
          label: Paiement
        is_manual:
          label: Manuel
      list:
        table_method: retrieveByClub
        display: [num, amount, is_payed, is_manual, tbl_club, tbl_typepayment]
        object_actions:
          payed:
            label: Réception Paiement
            credentials: [ValidLicence]
            params:
              confirm: Etes vous sur que le bordereau est réglé ?
          show:
            label: voir
            params:
              class: zoom_icon
        actions: {}
      filter:
        display: [num]
      form:    ~
      edit:    ~
      new:     ~
