generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tbl_typelicence
    theme:                 admin
    css:                   admin
    actions_base_class:    sfActions
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tbl_typelicence
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        rank:
            label: Ordre
        is_familly:
            label: Famille
        is_minor:
            label: Mineur
        tbl_grouplicence:
            label: Groupe
        id_group:
            label: Groupe
      list:
        title: Liste des types de licence
        display: [rank, lib, code, is_familly, is_minor, tbl_grouplicence]
        batch_actions: {}
        object_actions:
          movedown:
            label: 'Descencre'
            params:
              class: down_rank
          moveup:
            label: 'Monter'
            params:
              class: up_rank
          _edit: ~
          _delete:
            credentials: [admin]
      filter:
        display: [id_group, code, lib]
      form:
      edit:
        title: Edition du type de licence "%%lib%%"
        display: [lib, code, is_familly, is_minor, description, id_group, rank, prix]
      new:
        title: Nouveau type de licence
        display: [lib, code, is_familly, is_minor, description, id_group, rank, prix]
