<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('tbl_bordereau', 'tbl_bordereau_id_typepayment_tbl_typepayment_id', array(
             'name' => 'tbl_bordereau_id_typepayment_tbl_typepayment_id',
             'local' => 'id_typepayment',
             'foreign' => 'id',
             'foreignTable' => 'tbl_typepayment',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('tbl_bordereau', 'tbl_bordereau_id_club_tbl_club_id', array(
             'name' => 'tbl_bordereau_id_club_tbl_club_id',
             'local' => 'id_club',
             'foreign' => 'id',
             'foreignTable' => 'tbl_club',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('tbl_bordereau', 'tbl_bordereau_id_typepayment', array(
             'fields' => 
             array(
              0 => 'id_typepayment',
             ),
             ));
        $this->addIndex('tbl_bordereau', 'tbl_bordereau_id_club', array(
             'fields' => 
             array(
              0 => 'id_club',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('tbl_bordereau', 'tbl_bordereau_id_typepayment_tbl_typepayment_id');
        $this->dropForeignKey('tbl_bordereau', 'tbl_bordereau_id_club_tbl_club_id');
        $this->removeIndex('tbl_bordereau', 'tbl_bordereau_id_typepayment', array(
             'fields' => 
             array(
              0 => 'id_typepayment',
             ),
             ));
        $this->removeIndex('tbl_bordereau', 'tbl_bordereau_id_club', array(
             'fields' => 
             array(
              0 => 'id_club',
             ),
             ));
    }
}