<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('tbl_bordereau', 'num', 'string', '10', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('tbl_bordereau', 'num');
    }
}