<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('tbl_bordereau', 'id_club', 'integer', '4', array(
             ));
        $this->addColumn('tbl_bordereau', 'id_typepayment', 'integer', '4', array(
             ));
        $this->changeColumn('tbl_avoir', 'amount', 'float', '8', array(
             ));
        $this->changeColumn('tbl_bordereau', 'amount', 'float', '8', array(
             ));
        $this->changeColumn('tbl_payment', 'amount', 'float', '8', array(
             ));
        $this->changeColumn('tbl_prixunit', 'prix', 'float', '8', array(
             'notnull' => '1',
             ));
        $this->changeColumn('tbl_typelicence', 'prix', 'float', '8', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('tbl_bordereau', 'id_club');
        $this->removeColumn('tbl_bordereau', 'id_typepayment');
    }
}