<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('tbl_profil', 'image', 'string', '50', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('tbl_profil', 'image');
    }
}