<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('tbl_licence', 'lastname_doctor', 'string', '50', array(
             ));
        $this->addColumn('tbl_licence', 'firstname_doctor', 'string', '50', array(
             ));
        $this->addColumn('tbl_licence', 'rpps', 'string', '11', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('tbl_licence', 'lastname_doctor');
        $this->removeColumn('tbl_licence', 'firstname_doctor');
        $this->removeColumn('tbl_licence', 'rpps');
    }
}