<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('tbl_params', array(
             'id' =>
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'code' =>
             array(
              'type' => 'string',
              'length' => '20',
             ),
             'lib' =>
             array(
              'type' => 'string',
              'length' => '150',
             ),
             'description' =>
             array(
              'type' => 'string',
              'length' => '2000',
             ),
             ), array(
             'primary' =>
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('tbl_params');
    }
}