<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('tbl_prixlicence', array(
             'id' =>
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'prix' =>
             array(
              'type' => 'float',
              'notnull' => '1',
              'length' => '8',
             ),
             'id_typelicence' =>
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'id_federation' =>
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             ), array(
             'primary' =>
             array(
              0 => 'id',
             ),
             ));
        $this->createForeignKey('tbl_prixlicence', 'tbl_prixlicence_id_typelicence_tbl_typelicence_id', array(
             'name' => 'tbl_prixlicence_id_typelicence_tbl_typelicence_id',
             'local' => 'id_typelicence',
             'foreign' => 'id',
             'foreignTable' => 'tbl_typelicence',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('tbl_prixlicence', 'tbl_prixlicence_id_federation_tbl_federation_id', array(
             'name' => 'tbl_prixlicence_id_federation_tbl_federation_id',
             'local' => 'id_federation',
             'foreign' => 'id',
             'foreignTable' => 'tbl_federation',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('tbl_prixlicence', 'tbl_prixlicence_id_typelicence', array(
             'fields' =>
             array(
              0 => 'id_typelicence',
             ),
             ));
        $this->addIndex('tbl_prixlicence', 'tbl_prixlicence_id_federation', array(
             'fields' =>
             array(
              0 => 'id_federation',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('tbl_prixlicence');
    }
}