<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('tbl_club', 'tbl_club_id_federation_tbl_federation_id', array(
             'name' => 'tbl_club_id_federation_tbl_federation_id',
             'local' => 'id_federation',
             'foreign' => 'id',
             'foreignTable' => 'tbl_federation',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('tbl_club', 'tbl_club_id_federation', array(
             'fields' => 
             array(
              0 => 'id_federation',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('tbl_club', 'tbl_club_id_federation_tbl_federation_id');
        $this->removeIndex('tbl_club', 'tbl_club_id_federation', array(
             'fields' => 
             array(
              0 => 'id_federation',
             ),
             ));
    }
}