<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('tbl_club', 'id_federation', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('tbl_club', 'id_federation');
    }
}