generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tbl_club
    theme:                 admin
    css:                   admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tbl_club
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        address1:
          label: Adresse
        address2:
          label: Adresse complémentaire
        tel:
          label: Téléphone
        gsm:
          label: Portable
        username:
          label: Identifiant
          help: Pour la connexion
        id_gen:
          label: Titre
        name:
          label: Nom du club
        affiliation:
          label: Affiliation
        image_logo:
          label: Logo
        tbl_address:
          label: Adresse
        sfGuardUser:
          label: Utilisateur
        id_ligue:
          label: Ligue
        id_affectation:
          label: Affectation
        num:
          label: Numéro
        tbl_ligue:
          label: Ligue
        organisation:
          label: Organisateur de course
      list:
        title: Liste des clubs
        display: [_image_logo, num, sigle, name, sfGuardUser, tbl_ligue]
        max_per_page: 20
        batch_actions: {}
        object_actions:
          _edit: ~
          edit_password:
            label: Modifier mot de passe
          regulation:
            label: Règlement encours
            credentials: [admin]
          _delete:
            credentials: [admin]
      filter:
        display: [name, num, affiliation, id_affectation, id_ligue]
      form:
      edit:
        title: Edition du club %%name%%
        display:
          "NONE": [name, num, affiliation, id_affectation, id_ligue, sigle, logo]
          "Information utilisateur": [id_gen, email, username, nom, prenom]
          "Adresse": [id_codepostaux, address1, address2, tel, gsm, fax]
          "Divers": [organisation]
      new:
        title: Nouveau club
        display:
          "NONE": [name, num, affiliation, id_affectation, id_ligue, sigle, logo]
          "Information utilisateur": [id_gen, email, username, _generate_password, password, nom, prenom]
          "Adresse": [id_codepostaux, address1, address2, tel, gsm, fax]
          "Divers": [organisation]
