generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tbl_codepostaux
    theme:                 admin
    css:                   admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tbl_codepostaux
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Liste des villes
        display: [insee, ville, code_postaux]
        max_per_page: 40
        batch_actions: {}
        actions: {}
        object_actions:
          _edit:
            label: Modifier
      filter:
        display: [ville, code_postaux]
      form:
        display: [ville, code_postaux]
      edit:    ~
      new:     ~
