generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tbl_licence
    theme:                 admin
    css:                   admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tbl_licence
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        first_name:
          label: Prénom
        last_name:
          label: Nom
        birthday:
          label: Date anniversaire
        address1:
          label: Adresse
        address2:
          label: Adresse complémentaire
        tel:
          label: Téléphone
        gsm:
          label: Portable
        fax:
          label: Fax
        id_club:
          label: Club
        id_category:
          label: Catégorie
        id_familly:
          label: Tarif Famille
          help: Licence du tuteur
        id_typelicence:
          label: Type de licence
        is_familly:
          label: Famille
        date_medical:
          label: Date certificat médical
        tbl_club:
          label: Club
        tbl_category:
          label: Catégorie
        tbl_typelicence:
          label: Type de licence
        check_date:
          label: Validation
        tbl_profil:
          label: Licencié
        num:
          label: Numéro de licence
        is_brouillon:
          label: Brouillon (encours de saisie)
      list:
        title: Liste des licenciés
        display: [num, is_brouillon, tbl_profil, tbl_club, tbl_typelicence, tbl_category, _check_date]
        table_method: retrieveByClub
        max_per_page: 20
        batch_actions: {}
        actions:
          _new:
          valid_saisie:
          cancel_saisie:
          commande:
            credentials: [[account_club, account_ligue]]
        object_actions:
          _edit: ~
          valid_licence:
            credentials: [ValidLicence]
          _delete:
            credentials: [admin]
      filter:
        display: [num, id_typelicence, id_category]
      form:    ~
      edit:
        display:
          "Profile": [email, last_name, first_name, birthday, id_profil]
          "Adresse": [id_codepostaux, address1, address2, tel, gsm, fax, id_address]
          "Licence": [id_club, id_category, id_typelicence, international, race_nordique, id_familly, cnil, date_medical]
      new:
        display:
          "Chercher profil": [id_profil, _profil_exist]
          "Profile": [email, last_name, first_name, birthday]
          "Adresse": [id_codepostaux, address1, address2, tel, gsm, fax, id_address]
          "Licence": [id_club, id_category, id_typelicence, international, race_nordique, id_familly, cnil, date_medical]
