generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tbl_licence
    theme:                 admin
    css:                   admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tbl_licence
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Liste des licenciés
        display: [num, tbl_profil, tbl_typelicence, tbl_category]
        max_per_page: 20
        batch_actions: {}
        actions:
          _new:
            credentials: [licence]
          commande:
            credentials: [[account_club, account_ligue]]
        object_actions:
          _edit: ~
          valid_licence:
            credentials: [ValidLicence]
          _delete:
            credentials: [admin]
      filter:
        display: [num, id_typelicence, id_category]
      form:    ~
      edit:
        display:
          "Profile": [email, last_name, first_name, birthday]
          "Adresse": [id_codepostaux, address1, address2, tel, gsm, fax, id_address]
          "Licence": [id_club, id_category, id_typelicence, international, race_nordique, is_familly, cnil, date_medical]
      new:
        display:
          "Profile": [email, last_name, first_name, birthday]
          "Adresse": [id_codepostaux, address1, address2, tel, gsm, fax, id_address]
          "Licence": [id_club, id_category, id_typelicence, international, race_nordique, is_familly, cnil, date_medical]
