tbl_tracability:
  actAs:
    Timestampable: ~
  columns:
    id:             { type: integer(4), primary: true,  autoincrement: true }
    date_connexion: { type: timestamp }
    username:       { type: string(50) }
    ip:             { type: string(50) }
    is_connected:   { type: boolean, default: false }

tbl_ligue:
  actAs:
    Timestampable: ~
  columns:
    id:             { type: integer(4), primary: true,  autoincrement: true }
    name:           { type: string(50), notnull: true, unique: true }
    num:            { type: string(3), notnull: true, unique: true }
    affiliation:    { type: string(4), notnull: true }
    sigle:          { type: string(10) }
    logo:           { type: string(250) }
    organisation:   { type: boolean }
    id_address:     { type: integer(4) }
    id_user:        { type: integer }
    id_gen:         { type: integer(2) }
    id_affectation: { type: integer(2) }
  relations:
    sfGuardUser:     { onDelete: CASCADE, onUpdate: CASCADE, local: id_user, foreign: id, foreignAlias: tbl_ligue }
    tbl_address:     { onDelete: CASCADE, onUpdate: CASCADE, local: id_address, foreign: id, foreignAlias: tbl_ligue }
    tbl_gen:         { onDelete: CASCADE, onUpdate: CASCADE, local: id_gen, foreign: id, foreignAlias: tbl_ligue }
    tbl_affectation: { onDelete: CASCADE, onUpdate: CASCADE, local: id_affectation, foreign: id, foreignAlias: tbl_club }

tbl_club:
  actAs:
    Timestampable: ~
  columns:
    id:             { type: integer(4), primary: true,  autoincrement: true }
    name:           { type: string(50), notnull: true, unique: true }
    num:            { type: string(3), notnull: true, unique: true }
    affiliation:    { type: string(4), notnull: true }
    sigle:          { type: string(10) }
    logo:           { type: string(250) }
    organisation:   { type: boolean }
    id_address:     { type: integer(4) }
    id_user:        { type: integer }
    id_gen:         { type: integer(2) }
    id_ligue:       { type: integer(4) }
    id_affectation: { type: integer(2) }
  relations:
    sfGuardUser:     { onDelete: CASCADE, onUpdate: CASCADE, local: id_user, foreign: id, foreignAlias: tbl_club }
    tbl_address:     { onDelete: CASCADE, onUpdate: CASCADE, local: id_address, foreign: id, foreignAlias: tbl_club }
    tbl_gen:         { onDelete: CASCADE, onUpdate: CASCADE, local: id_gen, foreign: id, foreignAlias: tbl_club }
    tbl_ligue:       { onDelete: CASCADE, onUpdate: CASCADE, local: id_ligue, foreign: id, foreignAlias: tbl_club }
    tbl_affectation: { onDelete: CASCADE, onUpdate: CASCADE, local: id_affectation, foreign: id, foreignAlias: tbl_club }

tbl_affectation:
  columns:
    id:             { type: integer(2), primary: true,  autoincrement: true }
    code:           { type: string(1), notnull: true }
    lib:            { type: string(50), notnull: true }

tbl_address:
  actAs:
    Timestampable: ~
  columns:
    id:             { type: integer(4), primary: true,  autoincrement: true }
    address1:       { type: string(250), notnull: true }
    address2:       { type: string(250) }
    tel:            { type: string(20) }
    gsm:            { type: string(20) }
    fax:            { type: string(20) }
    country:        { type: string(2) }
    cp_foreign:     { type: string(50) }
    city_foreign:   { type: string(50) }
    id_codepostaux: { type: integer(6) }
  relations:
    tbl_codepostaux:   { onDelete: CASCADE, onUpdate: CASCADE, local: id_codepostaux, foreign: id, foreignAlias: tbl_address }

tbl_codepostaux:
  columns:
    id:             { type: integer(6), primary: true,  autoincrement: true }
    insee:          { type: string(5) }
    code_postaux:   { type: string(5), notnull: true }
    ville:          { type: string(250) }

tbl_gen:
  options:
    symfony:
      form:   false
      filter: false
  columns:
    id:             { type: integer(2), primary: true,  autoincrement: true }
    lib:            { type: string(4), notnull: true }

tbl_typelicence:
  columns:
    id:             { type: integer(4), primary: true,  autoincrement: true }
    lib:            { type: string(250), notnull: true }
    code:           { type: string(10), notnull: true }
    is_familly:     { type: boolean, default: false }
    is_minor:       { type: boolean, default: false }
    description:    { type: string(2000) }
    rank:           { type: integer }
    prix:           { type: float(8), notnull: true }
    id_group:       { type: integer(4) }
  relations:
    tbl_grouplicence:   { onDelete: CASCADE, onUpdate: CASCADE, local: id_group, foreign: id, foreignAlias: tbl_typelicence }

tbl_grouplicence:
  options:
    symfony:
      form:   false
      filter: false
  columns:
    id:             { type: integer(4), primary: true,  autoincrement: true }
    lib:            { type: string(250), notnull: true }
    code:           { type: string(3), notnull: true }

tbl_category:
  columns:
    id:             { type: integer(4), primary: true,  autoincrement: true }
    lib:            { type: string(250), notnull: true }
    code:           { type: string(10), notnull: true }

tbl_prixunit:
  columns:
    id:             { type: integer(4), primary: true,  autoincrement: true }
    lib:            { type: string(250), notnull: true }
    code:           { type: string(4), notnull: true }
    prix:           { type: float(8), notnull: true }

tbl_profil:
  actAs:
    Timestampable: ~
  columns:
    id:                { type: integer(4), primary: true,  autoincrement: true }
    last_name:         { type: string(50), notnull: true  }
    first_name:        { type: string(50), notnull: true  }
    id_address:        { type: integer(4) }
    email:             { type: string(150), notnull: true  }
    birthday:          { type: timestamp, notnull: true  }
    sexe:              { type: string(20) }
  relations:
    tbl_address:   { onDelete: CASCADE, onUpdate: CASCADE, local: id_address, foreign: id, foreignAlias: tbl_profil }

tbl_licence:
  actAs:
    Timestampable: ~
  columns:
    id:                { type: integer(4), primary: true,  autoincrement: true }
    num:               { type: string(17), notnull: true }
    is_new:            { type: boolean, default: true }
    is_brouillon:      { type: boolean, default: true }
    international:     { type: boolean, default: false }
    race_nordique:     { type: boolean, default: false }
    is_familly:        { type: boolean, default: false }
    id_familly:        { type: integer(4) }
    cnil:              { type: boolean, default: false }
    date_medical:      { type: timestamp }
    date_validation:   { type: timestamp }
    year_licence:      { type: string(9) }
    id_profil:         { type: integer(4), notnull: true  }
    id_club:           { type: integer(4), notnull: true  }
    id_category:       { type: integer(4) }
    id_typelicence:    { type: integer(4), notnull: true  }
    id_user:           { type: integer }
    is_cancel:         { type: boolean, default: false }
  relations:
    sfGuardUser:       { onDelete: CASCADE, onUpdate: CASCADE, local: id_user, foreign: id, foreignAlias: tbl_licence }
    tbl_profil:        { onDelete: CASCADE, onUpdate: CASCADE, local: id_profil, foreign: id, foreignAlias: tbl_licence }
    tbl_club:          { onDelete: CASCADE, onUpdate: CASCADE, local: id_club, foreign: id, foreignAlias: tbl_licence }
    tbl_category:      { local: id_category, foreign: id, foreignAlias: tbl_licence }
    tbl_typelicence:   { onDelete: CASCADE, onUpdate: CASCADE, local: id_typelicence, foreign: id, foreignAlias: tbl_licence }
    tbl_familly:       { class: tbl_profil, onDelete: CASCADE, onUpdate: CASCADE, local: id_familly, foreign: id, foreignAlias: tbl_licence }

tbl_payment:
  actAs:
    Timestampable: ~
  columns:
    id:                { type: integer(4), primary: true,  autoincrement: true }
    num:               { type: string(17) }
    date_payment:      { type: timestamp }
    is_brouillon:      { type: boolean, default: true }
    is_payed:          { type: boolean, default: false }
    lib:               { type: string(50) }
    description:       { type: string(250) }
    relation_table:    { type: string(50) }
    id_typepayment:    { type: integer(4) }
    amount:            { type: float(8) }
    id_licence:        { type: integer(4) }
    id_profil:         { type: integer(4) }
    id_club:           { type: integer(4) }
    id_ligue:          { type: integer(4) }
    id_bordereau:      { type: integer(4) }
    id_user:           { type: integer }
  relations:
    sfGuardUser:       { local: id_user, foreign: id, foreignAlias: tbl_payment }
    tbl_licence:       { onDelete: CASCADE, onUpdate: CASCADE, local: id_licence, foreign: id, foreignAlias: tbl_payment }
    tbl_profil:        { onDelete: CASCADE, onUpdate: CASCADE, local: id_profil, foreign: id, foreignAlias: tbl_payment }
    tbl_club:          { onDelete: CASCADE, onUpdate: CASCADE, local: id_club, foreign: id, foreignAlias: tbl_payment }
    tbl_ligue:         { onDelete: CASCADE, onUpdate: CASCADE, local: id_ligue, foreign: id, foreignAlias: tbl_payment }
    tbl_typepayment:   { onDelete: CASCADE, onUpdate: CASCADE, local: id_typepayment, foreign: id, foreignAlias: tbl_payment }
    tbl_bordereau:     { local: id_bordereau, foreign: id, foreignAlias: tbl_payment }

tbl_typepayment:
  options:
    symfony:
      form:   false
      filter: false
  actAs:
    Sluggable:
       fields: [lib]
       name: slug
       canUpdate: true
       unique: true
  columns:
    id:                { type: integer(4), primary: true,  autoincrement: true }
    lib:               { type: string(50) }

tbl_avoir:
  actAs:
    Timestampable: ~
  columns:
    id:                { type: integer(4), primary: true,  autoincrement: true }
    lib:               { type: string(50) }
    is_brouillon:      { type: boolean, default: true }
    amount:            { type: float(8) }
    relation_table:    { type: string(50) }
    is_used:           { type: boolean, default: false }
    id_typepayment:    { type: integer(4) }
    id_licence:        { type: integer(4) }
    id_profil:         { type: integer(4) }
    id_club:           { type: integer(4) }
    id_ligue:          { type: integer(4) }
    id_bordereau:      { type: integer(4) }
    id_user:           { type: integer }
  relations:
    tbl_licence:       { onDelete: CASCADE, onUpdate: CASCADE, local: id_licence, foreign: id, foreignAlias: tbl_avoir }
    sfGuardUser:       { local: id_user, foreign: id, foreignAlias: tbl_avoir }
    tbl_profil:        { onDelete: CASCADE, onUpdate: CASCADE, local: id_profil, foreign: id, foreignAlias: tbl_avoir }
    tbl_club:          { onDelete: CASCADE, onUpdate: CASCADE, local: id_club, foreign: id, foreignAlias: tbl_avoir }
    tbl_ligue:         { onDelete: CASCADE, onUpdate: CASCADE, local: id_ligue, foreign: id, foreignAlias: tbl_avoir }
    tbl_typepayment:   { onDelete: CASCADE, onUpdate: CASCADE, local: id_typepayment, foreign: id, foreignAlias: tbl_avoir }
    tbl_bordereau:     { local: id_bordereau, foreign: id, foreignAlias: tbl_avoir }

tbl_bordereau:
  columns:
    id:                { type: integer(4), primary: true,  autoincrement: true }
    lib:               { type: string(50) }
    num:               { type: string(10) }
    amount:            { type: float(8) }
    is_payed:          { type: boolean, default: false }
    id_user:           { type: integer }
    id_club:           { type: integer(4) }
    id_typepayment:    { type: integer(4) }
    is_manual:         { type: boolean, default: false }
  relations:
    sfGuardUser:       { onDelete: CASCADE, onUpdate: CASCADE, local: id_user, foreign: id, foreignAlias: tbl_bordereau }
    tbl_typepayment:   { onDelete: CASCADE, onUpdate: CASCADE, local: id_typepayment, foreign: id, foreignAlias: tbl_bordereau }
    tbl_club:          { onDelete: CASCADE, onUpdate: CASCADE, local: id_club, foreign: id, foreignAlias: tbl_payment }

tbl_saison:
  options:
    symfony:
      filter: false
  columns:
    id:                { type: integer(4), primary: true,  autoincrement: true }
    day_begin:         { type: integer(2), notnull: true }
    month_begin:       { type: integer(2), notnull: true }
    day_end:           { type: integer(2), notnull: true }
    month_end:         { type: integer(2), notnull: true }
    year_licence:      { type: string(9), notnull: true }
    is_outstanding:    { type: boolean, default: true }

tbl_comite:
  columns:
    id:                { type: integer(4), primary: true,  autoincrement: true }
    lib:               { type: string(50) }
    id_profil:         { type: integer(4), notnull: true }
    id_user:           { type: integer, notnull: true }
    id_position:       { type: integer(4) }
  relations:
    sfGuardUser:       { onDelete: CASCADE, onUpdate: CASCADE, local: id_user, foreign: id, foreignAlias: tbl_comite }
    tbl_profil:        { onDelete: CASCADE, onUpdate: CASCADE, local: id_profil, foreign: id, foreignAlias: tbl_comite }
    tbl_position:      { onDelete: CASCADE, onUpdate: CASCADE, local: id_position, foreign: id, foreignAlias: tbl_comite }

tbl_position:
  options:
    symfony:
      form: false
      filter: false
  columns:
    id:                { type: integer(4), primary: true,  autoincrement: true }
    lib:               { type: string(50), notnull: true }

tbl_mandat:
  columns:
    id:                { type: integer(4), primary: true,  autoincrement: true }
    date_begin:        { type: timestamp }
    date_end:          { type: timestamp }
    fonction_actuel:   { type: string(50) }
    id_profil:         { type: integer(4) }
  relations:
    tbl_profil:        { onDelete: CASCADE, onUpdate: CASCADE, local: id_profil, foreign: id, foreignAlias: tbl_mandat }